---
all:
  hosts:
    cluster:
      ansible_connection: local
      ansible_python_interpreter: python3.9
  vars:
    download_dir: '{{ playbook_dir }}/downloaded'
    download_tmp: '{{ download_dir }}/.ansible/tmp'
    openshift_project: ansible-tower
    db_deployment_name: tower-db
    pg_username: tower
    pg_database: tower
    pg_hostname: '{{ db_deployment_name }}.{{ openshift_project }}.svc.cluster.local'
    pg_port: 5432
    pg_sslmode: prefer
    storageclass: ocs-storagecluster-cephfs
    admin_user: admin
    admin_password: '{{ lookup("password", playbook_dir + "/downloaded/admin_password length=15") }}'
    secret_key: '{{ lookup("password", playbook_dir + "/downloaded/secret_key length=15") }}'
